In [1]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential, Model
from keras.layers import Dense, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, Input
from keras.utils import np_utils
from keras import backend as K
import matplotlib.pyplot as plt

# loss 그래프 그리는 함수
def plot_loss(history):
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('Model Loss')
    plt.ylabel('Loss')
    plt.xlabel('Epochs')
    plt.legend(['Train', 'val'], loc=0)

# accuracy 그래프 그리는 함수
def plot_acc(history):
    plt.plot(history.history['acc'])
    plt.plot(history.history['val_acc'])
    plt.title('Model accuracy')
    plt.ylabel('Accuracy')
    plt.xlabel('Epochs')
    plt.legend(['Train', 'val'], loc=0)

# 하이퍼파라미터 설정
batch_size = 128
nb_classes = 10
nb_epoch = 12

# 입력 이미지 사이즈 정보
img_rows, img_cols = 128, 128
# number of convolutional filters to use
nb_filters = 32

# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()
print(X_train)
# print("Training data:")
# print("Number of examples: ", X_train.shape[0])
# print("Image size:", X_train.shape[1], X_train.shape[2])
# print('\n')
# print("Test data:")
# print("Number of examples:", X_test.shape[0])
# print("Image size:", X_test.shape[1], X_test.shape[2])
# print('\n')

# # # mnist 데이터 이미지 추출 부분
# # plt.imshow(X_train[20].reshape(28, 28), cmap='Greys')
# # tmp = "Label:" + str(y_train[20])
# # plt.title(tmp, fontsize=30)
# # plt.tight_layout()
# # plt.show()

# # tensorflow backend 사용시 (Height, Width, channel) 순 입력 , Theano backend 사용시 (channel, Height, Width) 순 입력
# if K.image_dim_ordering() == 'th':
#     X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
#     X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
#     input_shape = (1, img_rows, img_cols)
# else:
#     X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
#     X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
#     input_shape = (img_rows, img_cols, 1)

# # 데이터 정규화 부분
# X_train = X_train.astype('float32')
# X_test = X_test.astype('float32')
# X_train /= 255
# X_test /= 255

# print(X_train.shape[0], 'train samples')
# print(X_test.shape[0], 'test samples')

# # 정답 label one-hot encoding
# Y_train = np_utils.to_categorical(y_train, nb_classes)
# Y_test = np_utils.to_categorical(y_test, nb_classes)

# model.compile(loss='categorical_crossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])

# history = model.fit(X_train, Y_train,
#                     batch_size=batch_size,
#                     epochs=nb_epoch,
#                     verbose=1,
#                     validation_split=0.2)

# print('\n')
# print('Test start')
# score = model.evaluate(X_test, Y_test, verbose=1)
# print('Test loss:', score[0])
# print('Test accuracy:', score[1])

# # 학습 loss 값 과 accuracy 결과 그래프
# plot_loss(history)
# plt.show()
# plot_acc(history)
# plt.show()

Using TensorFlow backend.
C:\Users\RentalHub-L5\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\RentalHub-L5\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\RentalHub-L5\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\RentalHub-L5\anaconda3\lib\site-packages\tensorflo

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [4]:
import os
import matplotlib.pyplot as plt
import numpy as np

In [7]:
cat_image = plt.imread('C:/Users/RentalHub-L5/Desktop/resize_left_ear/' + '00000001_000.jpg')

In [8]:
cat_image

array([[[109,  80,  74],
        [113,  84,  76],
        [117,  89,  78],
        ...,
        [117,  95,  82],
        [115,  93,  82],
        [113,  93,  82]],

       [[112,  83,  77],
        [113,  84,  76],
        [112,  84,  73],
        ...,
        [117,  93,  81],
        [115,  93,  80],
        [114,  92,  81]],

       [[114,  85,  79],
        [114,  85,  77],
        [112,  84,  73],
        ...,
        [118,  91,  80],
        [116,  92,  80],
        [115,  91,  79]],

       ...,

       [[ 85,  61,  51],
        [ 87,  63,  53],
        [ 85,  62,  56],
        ...,
        [154, 153, 151],
        [158, 157, 155],
        [158, 157, 155]],

       [[ 89,  60,  52],
        [ 90,  63,  56],
        [ 91,  66,  61],
        ...,
        [156, 155, 153],
        [152, 151, 149],
        [152, 151, 149]],

       [[ 88,  59,  51],
        [ 88,  61,  54],
        [ 91,  66,  61],
        ...,
        [159, 158, 156],
        [153, 152, 150],
        [153, 152, 150]]